### ISSUE TITLE
You may use enums for this configuration values

### ISSUE THREAD

**Issue by incredibleLeitman** [tscripca/SlotMachine#14]
https://github.com/tscripca/SlotMachine/blob/174684312f0974b8bdf164741ddecac081bb1ca1/SlotMachine/Program.cs#L12-L14
Take a look at the video in teachable:
https://course.raketementoring.com/courses/rakete-mentoring/lectures/45560170
This will make your code more readable and help you in some codeblocks to get rid of some magic numbers

**Comment by mayisa87** [comment]
The best way would be, to read as before an integer value from user, so the user chooses the int value on console. After reading, you can check, if this is a valid value, by checking, if it is one of the enum values. There is a predefined method, that checks if a given value is part of the enum, it is called isDefined  --> https://learn.microsoft.com/en-us/dotnet/api/system.enum.isdefined?view=net-7.0

To make it a bit easier and have not a lot of type casts everywhere in your code, you can store once the user input converted to enum as variable. So for example, if your enum would have the name LineType:

LineType typeChosen = (LineType)userChooseToPlay;

So you can use this variable then as you did use before the integer value in your if statements:
if(typeChosen == LineType.XY)

**Comment by mayisa87** [comment]
Another option could be the Enum.TryParse(), each enum has whether an fix integer value defined OR it has like an array or list an predefined index, so first defined element = 0, second =1 etc. 
If you give the first element of enum an "=1" the second will have 2, third 3 and so on.

The tryParse does just take the user input (for example 1, 2, 3 or whatever) and sees if the integer value of enum does match and returns the enum then. 

Here an example:

```
namespace ConsoleApp1
{
    internal class Program
    {

        public enum UserChoices
        {
            MyFirst,
            MySecond,
            MyThird
        };

        static void Main(string[] args)
        {
            string input = Console.ReadLine();
            UserChoices choice = UserChoices.MyFirst;
            Enum.TryParse(input, out choice);

        }
    }
}
```

**Comment by mayisa87** [comment]
close this, and continue with issue #21 ;) The enum is now implemented, now it is about right usage
