### ISSUE TITLE
extract user interaction to ui methods

### ISSUE THREAD

**Issue by incredibleLeitman** [tscripca/SlotMachine#34]
https://github.com/tscripca/SlotMachine/blob/3f7b5e552e506b79a1bab564b8bfb588ca35ec51/SlotMachine/Program.cs#L27
https://github.com/tscripca/SlotMachine/blob/3f7b5e552e506b79a1bab564b8bfb588ca35ec51/SlotMachine/Program.cs#L28
https://github.com/tscripca/SlotMachine/blob/3f7b5e552e506b79a1bab564b8bfb588ca35ec51/SlotMachine/Program.cs#L66
https://github.com/tscripca/SlotMachine/blob/3f7b5e552e506b79a1bab564b8bfb588ca35ec51/SlotMachine/Program.cs#L67

There should be no "Console.X" calls remaining in any other files than the one for UI methods

**Comment by mayisa87** [comment]
Related to issue #32

**Comment by tscripca** [comment]
Closed on issue #32
