### ISSUE TITLE
Naming of methods

### ISSUE THREAD

**Issue by mayisa87** [tscripca/SlotMachine#38]
https://github.com/tscripca/SlotMachine/blob/3f7b5e552e506b79a1bab564b8bfb588ca35ec51/SlotMachine/LogicMethods.cs#L106

Methods are named always starting with a verb and then should describe what they are doing.

So GridGenerator is no valid method name. It could be "FillSlotMachineValues" or "GenerateSlotMachineValues" or "FillSlotArray" etc.

See this article: https://csharp-book.softuni.org/Content/Chapter-10-methods/method-naming/method-naming.html

**Comment by tscripca** [comment]
issue closed on #36
