### ISSUE TITLE
Random object can be public static

### ISSUE THREAD

**Issue by mayisa87** [tscripca/SlotMachine#40]
https://github.com/tscripca/SlotMachine/blob/3f7b5e552e506b79a1bab564b8bfb588ca35ec51/SlotMachine/LogicMethods.cs#L109

This is one of the rare  cases where you can define a public static field :) You can make it even readonly, like: 

`public static readonly Random rng = new Random;`

The benefit, you can use this rng object then if needed also from other classes. And in general, you should use one random object to create all random numbers in your application. So more or less, the Random object rng is then like a constant, that can be used from everywhere :)

**Comment by tscripca** [comment]
Closed in issue #31 and #39, random object has been defined as public readonly.
