### ISSUE TITLE
Comparing the values of the first row

### ISSUE THREAD

**Issue by tscripca** [tscripca/SlotMachine#5]
I am using a for loop to print the first line of the slot machine but I don't know how to compare the indexes, to check for mathces in the same line.

**Comment by mayisa87** [comment]
Currently you got only one loop to loop through rows. You will need a nested inner loop for columns, as you want to access each value in row.

This works currently, as your  grid has the same amount of rows and columns, if this wouldn't be the case, it wouldn't work anymore. Imagine a grid of 10x3 for example, it would lead to an error if you access grid[9,9] for example, as you got only 3 columns!

So if you loop horizontal or vertical through your lines, you always need two loops like you already use it when filling values into the grid!

```
 for (rowIndex = 0; rowIndex < slotMachine.GetLength(0); rowIndex++)
{
     //THIS IS EXECUTED FOR EACH ROW
      for (columnIndex = 0; columnIndex < slotMachine.GetLength(1); columnIndex++)
      {
         //THIS IS EXECUTED FOR EACH COLUMN IN ROW (EACH CELL)
          Console.Write(slotMachine[rowIndex, columnIndex] + " ");
      }
      Console.WriteLine();
}
```
How to compare values of one line:
You can compare all values in line (inner loop) against the first value in current row.

What is the first value of current row? slotMachine[rowIndex,0] ---> rowIndex accesses current line/row. 0 always column 0, so first column value in line!

So you can always compare the first value against the current column value in inner loop slotMachine[rowIndex,columnIndex] != slotMachine[rowIndex,0], if the values do not match any longer, set a boolean variable to false and break, so you know that this line not all values matched
