### ISSUE TITLE
Remove jpg/png from GitHub

### ISSUE THREAD

**Issue by mayisa87** [tscripca/SlotMachine#7]
![image](https://github.com/tscripca/SlotMachine/assets/130921606/7db2d1b8-a250-4fab-b8c0-09194c594e59)

Please remove those files from GitHub if not needed. You open your project folder in a windows explorer window and delete the files. VS will show you those files as change and you can commit it then.

![image](https://github.com/tscripca/SlotMachine/assets/130921606/ba7539a8-92dc-4a4e-8dc4-54123b8a8a27)

**Comment by tscripca** [comment]
Closed #7
